// ============================================================
// FILE (NUOVO): lib/constants/roles.ts
// ============================================================

export const COMMON_ROLES = [
  "Tecn: architetto",
  "Tecn: ing. strutturista",
  "Tecn: ing. meccanico",
  "Tecn: ing. informatico",
  "Tecn: ing. elettrico",
  "Tecn: ing. agrario",
  "Tecn: tecn. ITACA",
  "Tecn: ing. elettronico",
  "Tecn: perito industriale",
  "Tecn: perito meccanico",
  "Tecn: perito elettrico",
  "Tecn: ing. gestionale",
  "Tecn: tecnico 818",
  "Tecn: geologo",
  "Tecn: Coordinatore sicurezza cantieri",
  "Tecn: tecnico rspp",
  "Tecn: geometra",
  "Tecn: Tecnico ITACA",
  "Tecn: ing. edile",
  "Tecn: tecnico sic. sul lavoro",
  "Tecn: Direzione Lavori",

  "Imp: Edile",
  "Imp: Construzioni",
  "Imp: Idraulica",
  "Imp: Termoidraulica",
  "Imp: Consulenza Finanza Agevolata",
  "Imp: Controsoffitti e Pareti in Cartongesso",
  "Imp: Elettrica",
  "Imp: Elettronica",
  "Imp: Acustica",
  "Imp: Falegnameria",
  "Imp: Arredamento",
  "Imp: Serramenti",
  "Imp: Allestimento Commerciale",

  "Ente: Comune (CILA/SCIA)",
  "Ente: Soprintendenza ai beni culturali",
  "Ente: Genio Civile",
  "Ente: ASL",
  "Ente: ARPA",
  "Ente: Ufficio Ambiente",
  "Ente: SPESAL",
  "Ente: Ispett. del lavoro",
  "Ente: Veterinaria",
  "Ente: Città metropolitana",
  "Ente: SISP",
  "Ente: SIAN",
  "Ente: Vigili Del Fuoco",
  "Ente: Ripartizione Edilizia",
  "Ente: Ripartizione Impianti",

] as const;
